spring:
  application:
    name: callback-handler

b2b:
  datasource:
    url: jdbc:postgresql://localhost:5432/qwikpe-b2b
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

b2c:
  datasource:
    url: jdbc:postgresql://localhost:5432/qwikpe-b2c
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    path: /home/ubuntu/logs/callback-handler

server:
  port: 9092

secret:
  abdm:
    clientId: SBXID_007285
    clientSecret: 25a4bf63-da0c-486c-aa53-ce9bd4fbe54a