spring:
  application:
    name: callback-handler
  datasource:
    url: jdbc:postgresql://localhost:5432/qwikpe-master-data
    username: postgres
    password: root

logging:
  file:
    path: /home/ubuntu/logs/callback-handler

server:
  port: 9092